/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful login */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tables */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tables */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TablesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrdersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            expiresIn?: string;
        };
        Table: {
            id: number;
            tableNumber: number;
            capacity: number;
            additionalCapacity: number;
            isOccupied: boolean;
            /** @enum {string} */
            status: "AVAILABLE" | "OCCUPIED" | "RESERVED" | "ORDERING" | "SERVING" | "PAYMENT";
            guests: number;
            originalCapacity: number;
            orders?: {
                id: number;
                /** Format: date-time */
                orderTime: string;
                /** @enum {string} */
                status?: "AWAITING" | "RECEIVED" | "SERVED" | "CANCELED" | "DISPUTED" | "READY_TO_PAY" | "COMPLETED";
            }[];
            assignment?: {
                serverId: number;
                isPrimary?: boolean;
            }[];
        };
        TableAssignment: {
            serverId: number;
            isPrimary?: boolean;
            assignedTables: number[];
        };
        Order: {
            id: number;
            tableNumber: number;
            orderNumber: number;
            guestsCount: number;
            /** Format: date-time */
            orderTime: string;
            /** Format: date-time */
            updatedAt: string;
            allergies?: ("GLUTEN" | "DAIRY" | "EGG" | "PEANUT" | "TREENUT" | "FISH" | "SHELLFISH" | "SOY" | "SESAME" | "CELERY" | "MUSTARD" | "LUPIN" | "SULPHITES" | "MOLLUSCS")[];
            serverId: number;
            totalAmount?: number;
            /** @enum {string} */
            status?: "AWAITING" | "RECEIVED" | "SERVED" | "CANCELED" | "DISPUTED" | "READY_TO_PAY" | "COMPLETED";
            comments: string;
            /** Format: date-time */
            completionTime: string;
            discount?: number;
            tip?: number;
            shiftId: string;
        };
        TablesResponse: {
            id: number;
            tableNumber: number;
            capacity: number;
            additionalCapacity: number;
            isOccupied: boolean;
            /** @enum {string} */
            status: "AVAILABLE" | "OCCUPIED" | "RESERVED" | "ORDERING" | "SERVING" | "PAYMENT";
            guests: number;
            originalCapacity: number;
            orders?: {
                id: number;
                /** Format: date-time */
                orderTime: string;
                /** @enum {string} */
                status?: "AWAITING" | "RECEIVED" | "SERVED" | "CANCELED" | "DISPUTED" | "READY_TO_PAY" | "COMPLETED";
            }[];
            assignment?: {
                serverId: number;
                isPrimary?: boolean;
            }[];
        }[];
        OrdersResponse: {
            id: number;
            tableNumber: number;
            orderNumber: number;
            guestsCount: number;
            /** Format: date-time */
            orderTime: string;
            /** Format: date-time */
            updatedAt: string;
            allergies?: ("GLUTEN" | "DAIRY" | "EGG" | "PEANUT" | "TREENUT" | "FISH" | "SHELLFISH" | "SOY" | "SESAME" | "CELERY" | "MUSTARD" | "LUPIN" | "SULPHITES" | "MOLLUSCS")[];
            serverId: number;
            totalAmount?: number;
            /** @enum {string} */
            status?: "AWAITING" | "RECEIVED" | "SERVED" | "CANCELED" | "DISPUTED" | "READY_TO_PAY" | "COMPLETED";
            comments: string;
            /** Format: date-time */
            completionTime: string;
            discount?: number;
            tip?: number;
            shiftId: string;
        }[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
